### ISSUE TITLE
Failed to compile. 

### ISSUE THREAD

**Issue by benzzamakon** [docusign/eg-02-react-implicit-grant#1]
How to solve ?
```Failed to compile. 
./src/index.js
Syntax error: C:/Users/benzaza/test/eg-02-react-implicit-grant-master/src/index.js: Unexpected token, expected : (17:110)

  15 | import sendSignEnvReducer from './store/reducers/sendSignEnv';
  16 |
> 17 | const composeEnhancers = process.env.NODE_ENV === 'development' ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ as typeof compose || compose;
     |                                                                                                               ^
  18 | //const composeEnhancers = process.env.NODE_ENV === 'development' ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ : null || compose;
  19 |
```

**Comment by LarryKlugerDS** [comment]
Just now, I cloned the repo, npm install, npm start, and everything worked fine.

Perhaps the issue is that you are using more current versions of some of the libraries and the new library versions have introduced breaking changed from the older versions used to build the example. 

Unfortunately we don't have a React developer available to update the example to the current library versions. A pull request would be greatly appreciated!

Thank you for developing with DocuSign.

**Comment by benzzamakon** [comment]
Is there a solution, such as a workable version?
